# Generated by Django 4.1.3 on 2022-11-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_head_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file_upload',
            field=models.ImageField(blank=True, upload_to='blog/files/%Y/%m/%d/'),
        ),
    ]
